server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product_db
    username: root
    password: Password@@1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT-SERVICE

  config:
    import: configserver:http://localhost:9296

  cloud:
    compatibility-verifier:
      enabled: false

#  eureka:
#    client:
#      fetch-registry: true
#      register-with-eureka: true
##      with client we make these as true as it needs to connect with server
#      service-url:
#        defaultZone: http://localhost:8761/eureka



#spring.jpa.hibernate.ddl-auto=update

