server:
  port: 9296

spring:
  application:
    name: CONFIG_SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravipatiss/spring-app-config.git
          clone-on-start: true
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      #      with client we make these as true as it needs to connect with server
      service-url:
        defaultZone: http://localhost:8761/eureka

