server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order_db
    username: root
    password: Password@@1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: ORDER_SERVICE

  config:
    import: configserver:http://localhost:9296

  cloud:
    compatibility-verifier:
      enabled: false
okta:
  oauth2:
    issuer: https://dev-24143903.okta.com/oauth2/default
    audience: api://default
    client-id: 0oah7unkrd8CdXGzF5d7
    client-secret: Pyq-k2m4QnF4EVsYtIjkWOR-1PnmTh48IEIFQ2izlpBrvuKDQACIcqYxfBpGvvXs
    scopes: openid, profile, email, offline_access
#  eureka:
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      #      with client we make these as true as it needs to connect with server
#      service-url:
#        defaultZone: http://localhost:8761/eureka